### ISSUE TITLE
Yarn fails with Node v23

### ISSUE THREAD

**Issue by sfan5** [thelounge/thelounge#4971]
- _Node version:_ v23.11.0
- _Browser version:_ n/a
- _Device, operating system:_ Linux x86_64
- _The Lounge version:_ from git

---

```
root@2dcf6c21ce9a:/tmp/thelounge# yarn build
yarn run v1.22.22
$ run-p --aggregate-output build:client build:server
[webpack-cli] Failed to load '/tmp/thelounge/webpack.config.ts' config
[webpack-cli] Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/tmp/thelounge/server/helper' imported from /tmp/thelounge/webpack.config.ts
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:780:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:704:25)
    at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:739:38)
    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:762:52)
    at #cachedResolveSync (node:internal/modules/esm/loader:723:25)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:451:50)
    at new ModuleJobSync (node:internal/modules/esm/module_job:344:34) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///tmp/thelounge/server/helper'
}
error Command failed with exit code 2.                                                                 
$ webpack
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:client" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brunnre8** [comment]
works with v24.8.0 for me, as well as the 22 LTS, so I'm inclined to ignore it
